### ISSUE TITLE
Falta subir la clase DaggerMainComponent

### ISSUE THREAD

**Issue by mmaneff** [erikcaffrey/Clean-Architecture-Android#1]
Hola, te quería comentar que descargue el fuente y me percate que esta faltando subir la clase DaggerMainComponent en el pakages .....di.components.DaggerMainComponent.
Por favor, cuando este listo estaría bueno poder bajar lo que falta para ver la aplicación funcionando

**Comment by erikcaffrey** [comment]
@mmaneff hola Mateo! El proyecto funciona correctamente esa clase es generada en tiempo de compilación por dagger 2 lo que debes hacer es en ir a la puesta de build -> rebuild project y eso debería ser suficiente. Saludos y gracias por pasar por este repositorio!

**Comment by mmaneff** [comment]
Desde ya te agradezco que la respuesta y disculpa la ignorancia pues no
conozco ni manejo Dagger.

Estoy actualmente migrando mi app para usar el Patrón MVP y estoy
aprendiendo cosas nuevas.

Por otro lado me gustaría consultarte sobre un tema en particular si puede
ser. Estoy necesitando crear un Circular Progress Bar que me indique con 3
colores distintos el progreso. Muy similar al que podrías ver en Prana
Breath.
Si puedes darme una mano con ese tema te estaría muy agradecido.

Saludos y desde ya buen articulo.

2017-01-11 10:42 GMT-03:00 Erik Jhordan Rey <notifications@github.com>:

**Comment by erikcaffrey** [comment]
@mmaneff https://erikcaffrey.github.io/ANDROID-kata-dagger2/
